version: "3"
services:
  airflow:
    build:
      context: ./
      dockerfile: Dockerfile.airflow
    image: airflowimage
    container_name: gemstone-prediction-airflow
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
    user: "${AIRFLOW_UID:-50000}:0"

    environment:
      AIRFLOW__WEBSERVER__WORKERS: 1
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

    command: >
      bash -c "airflow db init && airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin123 && airflow webserver --port 8080 & airflow scheduler"
    
  flaskapp:
    build:
      context: ./
      dockerfile: Dockerfile.flask
    image: flaskimage
    container_name: gemstone-prediction-flask
    ports:
      - "80:80"
  
  mlflow:
    build:
      context: ./
      dockerfile: Dockerfile.flask
    image: flaskimage
    container_name: gemstone-prediction-mlflow
    ports:
      - "5001:5000"
    volumes:
      - ./mlruns:/app/mlruns
    command: >
      bash -c "
      mlflow ui \
        --host 0.0.0.0 \
        --port 5000 \
        --allowed-hosts '*' \
        --backend-store-uri sqlite:///mlflow.db
      "
    