# Dockerfile.mlflow

FROM python:3.10

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install mlflow

COPY . .

EXPOSE 5000

CMD ["mlflow", "server",
     "--host", "0.0.0.0",
     "--port", "5000",
     "--backend-store-uri", "sqlite:///mlflow.db",
     "--default-artifact-root", "/app/mlruns"]