version: "3"
services:
  airflow:
    build:
      context: ./
      dockerfile: Dockerfile.airflow
    image: airflowimage
    container_name: gemstone-prediction-airflow
    ports:
      - "8080:8793"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    user: "${AIRFLOW_UID:-50000}:0"
    command: bash -c "rm -f /opt/airflow/airflow-webserver.pid && airflow standalone"
    
  flaskapp:
    build:
      context: ./
      dockerfile: Dockerfile.flask
    image: flaskimage
    container_name: gemstone-prediction-flask
    ports:
      - "80:80"
    