version: "3"
services:
  airflow:
    build:
      context: ./
      dockerfile: Dockerfile.airflow
    image: airflowimage
    container_name: gemstone-prediction-airflow
    ports:
      - "8080:8080"
    
  flaskapp:
    build:
      context: ./
      dockerfile: Dockerfile.flask
    image: flaskimage
    container_name: gemstone-prediction-flask
    ports:
      - "80:80"
  
  mlflow:
    build:
      context: ./
      dockerfile: Dockerfile.mlflow
    image: mlflowimage
    container_name: gemstone-prediction-mlflow
    ports:
      - "5001:5000"
    volumes:
      - ./mlruns:/app/mlruns
    command: >
      bash -c "
      mlflow server \
        --host 0.0.0.0 \
        --port 5000 \
        --allowed-hosts '*' \
        --backend-store-uri sqlite:///mlflow.db
      "
    